dataset:
  path: electricity_data/processed_power_usage.csv
  valid_boundary: 1315
  test_boundary: 1339

feature_description:
  id: id
  time: hours_from_start
  target: power_usage
  known_continuous:
    - hour
    - day_of_week
    - hours_from_start
  known_categorical: []
  static_categorical:
    - categorical_id
  static_continuous: []
  observed_continuous: []
  observed_categorical: []

dataloader:
  batch_size: 64
  num_workers: 5
  pin_memory: true

model:
  encoder_length: 168 # 48
  decoder_length: 24
  d_model: 160 # 16
  dropout: 0.1
  n_head: 4 # 1 
  quantiles: [0.1, 0.5, 0.9]

training:
  epochs: 100
  learning_rate: 0.001
  grad_clip: 0.01
  multiprocessing_workers: 5
  early_stopping_patience: 5
  early_stopping_min_delta: 0.0001
  device: auto
  log_dir: runs
  log_every: 1000
  log_val: true
  log_val_every: 6000

wandb:
  enabled: true
  project: tft
  entity: null
  name: null
  mode: online
  tags: []
  notes: ""
