dataset:
  path: velib_data/velib_dataset.csv
  valid_boundary: 1615136340
  test_boundary: 1616783760
  step_seconds: 1200

feature_description:
  id: station_id
  time: date_seconds
  target: available_bikes
  known_continuous:
    - minutes_of_day
    - day_of_week
    - date_seconds
  known_categorical: 
    - is_public_holiday
  static_categorical:
    - station_id
    - zipcode
  static_continuous: 
    - latitude
    - longitude
    - capacity
  observed_continuous: 
    - temp
    - wind
    - snow
    - rain
  observed_categorical: []

dataloader:
  batch_size: 256
  num_workers: 8
  pin_memory: true

model:
  encoder_length: 168 # 48
  decoder_length: 24
  d_model: 160 # 16
  dropout: 0.1
  n_head: 4 # 1 
  quantiles: [0.1, 0.5, 0.9]

training:
  epochs: 100
  learning_rate: 0.001
  grad_clip: 10
  multiprocessing_workers: 5
  early_stopping_patience: 5
  early_stopping_min_delta: 0.0001
  device: cpu
  log_dir: runs
  log_every: 1000
  log_val: true
  log_val_every: 6000

wandb:
  enabled: false
  project: tft
  entity: null
  name: null
  mode: online
  tags: []
  notes: ""
